### ISSUE TITLE
not working, payment also not working

### ISSUE THREAD

**Issue by mounta11n** [harshalranjhani/genie#3]
hey buddy, i was curious to try out your app, unfortunately it doesn't work for me yet. For example, `genie chat` first wants me to verify my email -> this in turn implies that I am a supporter. I tried to pay a small amount with my credit card, but I get the error “International cards not supported”.

The command `genie do ..` does not require verification, but there I get the error: `2024/09/21 21:06:38 googleapi: Error 429: Resource has been exhausted (e.g. check quota).`, but I still have enough quota at google.

Do you have any idea what the problem is?

**Comment by harshalranjhani** [comment]
hii!! thanks for trying it out, currently the payment integration is done using razorpay so it might not support international payments. i am planning to move it to strip soon, although if you’re really keen about it, send me an email and i’ll add your account as a paid supporter!

also about the do command error, it’s related to your api key, just check the limits once, and also make sure you’re not running the command in your top level directory since you can’t directly run commands there without sudo permissions.

If you have any more questions feel free to reach out to me at genie@harshalranjhani.in.

Here is the genie documentation if you want to explore further - https://docs.genie.harshalranjhani.in
